#!/bin/bash

if [ $# -ne 3 ]
then
	echo "Usage: ./rdpWin host_addr user password"
	exit 1
fi

host=$1
res='2048x1350'
user=$2
pswd=$3

echo 'Connecting via RDP to WinVM @' $host

xfreerdp /dynamic-resolution +drives /size:$res /v:$host /u:$user /p:$pswd
